# This file was automatically generated by converter.py on
# 2013-05-31 13:50:53.491694. Think long and hard before
# attempting to modify it.

from components.helpers import *


class IBioDiversityState(Parameters):
    nospecies = IVariable1Dimensional('nospecies', [
                                      'Timestep'], 'double', 'Number of species')
    temp = IParameter1Dimensional('temp', [
                                  'Timestep'], 'double', 'Temperature')

    options = [nospecies, temp]


class BioDiversityComponent(Behaviors):
    state_class = IBioDiversityState

    def run(self, state, clock):

        s = (state)
        t = (clock.Current)

        if (t > clock.FromYear(2000)):

            dt = (math.abs(s.temp[t] - s.temp[t - 1]))

            s.nospecies[t] = (math.max(
                              s.nospecbase / 100,
                              s.nospecies[t - 1] * (
                              1.0 - s.bioloss - s.biosens * dt * dt / s.dbsta / s.dbsta)
                              ))

        else:
            s.nospecies[t] = (s.nospecbase)


behavior_classes = [BioDiversityComponent]
