# This file was automatically generated by converter.py on
# 2013-05-31 13:50:54.590389. Think long and hard before
# attempting to modify it.

from components.helpers import *


class IClimateDynamicsState(Parameters):
    radforc = IParameter1Dimensional('radforc', [
                                     'Timestep'], 'double', 'Total radiative forcing')
    temp = IVariable1Dimensional('temp', [
                                 'Timestep'], 'double', 'Average global temperature')

    options = [radforc, temp]


class ClimateDynamicsComponent(Behaviors):
    state_class = IClimateDynamicsState

    def run(self, state, clock):

        s = (state)
        t = (clock.Current)

        if (clock.IsFirstclock):

            s.temp[t] = (0.20)

        else:

            LifeTemp = (math.max(s.LifeTempConst + s.LifeTempLin * s.ClimateSensitivity + s.LifeTempQd * math.pow(
                s.ClimateSensitivity, 2.0), 1.0))

            delaytemp = (1.0 / LifeTemp)

            temps = (s.ClimateSensitivity / 5.35 / math.log(2.0))

            dtemp = (delaytemp * temps * s.radforc[
                     t] - delaytemp * s.temp[t - 1])

            s.temp[t] = (s.temp[t - 1] + dtemp)


behavior_classes = [ClimateDynamicsComponent]
