# This file was automatically generated by converter.py on
# 2013-05-31 13:50:55.547112. Think long and hard before
# attempting to modify it.

from components.helpers import *


class IClimateSO2CycleState(Parameters):
    globso2 = IParameter1Dimensional('globso2', [
                                     'Timestep'], 'double', 'Global SO2 emissions')
    acso2 = IVariable1Dimensional('acso2', [
                                  'Timestep'], 'double', 'Atmospheric SO2 concentration')

    options = [globso2, acso2]


class ClimateSO2CycleComponent(Behaviors):
    state_class = IClimateSO2CycleState

    def run(self, state, clock):

        s = (state)
        t = (clock.Current)

        if (clock.IsFirstclock):

            pass

        else:

            s.acso2[t] = (s.globso2[t])


behavior_classes = [ClimateSO2CycleComponent]
