# This file was automatically generated by converter.py on
# 2013-11-05 21:16:22.709212. Think long and hard before
# attempting to modify it.

import math
from components.helpers import *
from components._patches import *


class IImpactSeaLevelRiseState(Parameters):
    wetval = IVariable2Dimensional(
        'wetval', ['Timestep', 'Region'], 'double', None)
    wetlandloss = IVariable2Dimensional(
        'wetlandloss', ['Timestep', 'Region'], 'double', None)
    cumwetlandloss = IVariable2Dimensional(
        'cumwetlandloss', ['Timestep', 'Region'], 'double', None)
    wetlandgrowth = IVariable2Dimensional(
        'wetlandgrowth', ['Timestep', 'Region'], 'double', None)
    wetcost = IVariable2Dimensional(
        'wetcost', ['Timestep', 'Region'], 'double', None)
    dryval = IVariable2Dimensional(
        'dryval', ['Timestep', 'Region'], 'double', None)
    landloss = IVariable2Dimensional(
        'landloss', ['Timestep', 'Region'], 'double', None)
    cumlandloss = IVariable2Dimensional(
        'cumlandloss', ['Timestep', 'Region'], 'double', None)
    drycost = IVariable2Dimensional(
        'drycost', ['Timestep', 'Region'], 'double', None)
    npprotcost = IVariable2Dimensional(
        'npprotcost', ['Timestep', 'Region'], 'double', None)
    npwetcost = IVariable2Dimensional(
        'npwetcost', ['Timestep', 'Region'], 'double', None)
    npdrycost = IVariable2Dimensional(
        'npdrycost', ['Timestep', 'Region'], 'double', None)
    protlev = IVariable2Dimensional(
        'protlev', ['Timestep', 'Region'], 'double', None)
    protcost = IVariable2Dimensional(
        'protcost', ['Timestep', 'Region'], 'double', None)
    enter = IVariable2Dimensional(
        'enter', ['Timestep', 'Region'], 'double', None)
    leave = IVariable2Dimensional(
        'leave', ['Timestep', 'Region'], 'double', None)
    entercost = IVariable2Dimensional(
        'entercost', ['Timestep', 'Region'], 'double', None)
    leavecost = IVariable2Dimensional(
        'leavecost', ['Timestep', 'Region'], 'double', None)
    imigrate = IVariable2Dimensional(
        'imigrate', ['Region', 'Region'], 'double', None)
    pc = IParameter1Dimensional('pc', ['Region'], 'double', None)
    slrprtp = IParameter1Dimensional('slrprtp', ['Region'], 'double', None)
    wmbm = IParameter1Dimensional('wmbm', ['Region'], 'double', None)
    dlbm = IParameter1Dimensional('dlbm', ['Region'], 'double', None)
    drylandlossparam = IParameter1Dimensional(
        'drylandlossparam', ['Region'], 'double', None)
    wlbm = IParameter1Dimensional('wlbm', ['Region'], 'double', None)
    coastpd = IParameter1Dimensional('coastpd', ['Region'], 'double', None)
    wetmax = IParameter1Dimensional('wetmax', ['Region'], 'double', None)
    wetland90 = IParameter1Dimensional('wetland90', ['Region'], 'double', None)
    maxlandloss = IParameter1Dimensional(
        'maxlandloss', ['Region'], 'double', None)
    sea = IParameter1Dimensional('sea', ['Timestep'], 'double', None)
    migrate = IParameter2Dimensional(
        'migrate', ['Region', 'Region'], 'double', None)
    income = IParameter2Dimensional(
        'income', ['Timestep', 'Region'], 'double', None)
    population = IParameter2Dimensional(
        'population', ['Timestep', 'Region'], 'double', None)
    area = IParameter2Dimensional(
        'area', ['Timestep', 'Region'], 'double', None)
    incdens = ScalarVariable('incdens', 'double', None)
    emcst = ScalarVariable('emcst', 'double', None)
    immcst = ScalarVariable('immcst', 'double', None)
    dvydl = ScalarVariable('dvydl', 'double', None)
    wvel = ScalarVariable('wvel', 'double', None)
    wvbm = ScalarVariable('wvbm', 'double', None)
    slrwvpopdens0 = ScalarVariable('slrwvpopdens0', 'double', None)
    wvpdl = ScalarVariable('wvpdl', 'double', None)
    wvsl = ScalarVariable('wvsl', 'double', None)
    dvbm = ScalarVariable('dvbm', 'double', None)
    slrwvypc0 = ScalarVariable('slrwvypc0', 'double', None)

    options = [
        wetval, wetlandloss, cumwetlandloss, wetlandgrowth, wetcost, dryval, landloss, cumlandloss, drycost, npprotcost, npwetcost, npdrycost, protlev, protcost, enter, leave, entercost, leavecost, imigrate, pc,
        slrprtp, wmbm, dlbm, drylandlossparam, wlbm, coastpd, wetmax, wetland90, maxlandloss, sea, migrate, income, population, area, incdens, emcst, immcst, dvydl, wvel, wvbm, slrwvpopdens0, wvpdl, wvsl, dvbm, slrwvypc0]


class ImpactSeaLevelRiseComponent(Behaviors):
    state_class = IImpactSeaLevelRiseState

    def run(self, state, clock, dimensions):

        s = (state)
        t = (clock.Current)

        if (clock.IsFirstTimestep):

            for r1 in dimensions.GetValuesOfRegion():

                for r2 in dimensions.GetValuesOfRegion():
                    immsumm = (0)
                    for i in dimensions.GetValuesOfRegion():

                        immsumm += s.migrate[i, r1]

                    s.imigrate[r1, r2] = (s.migrate[r2, r1] / immsumm)

                t0 = (clock.StartTime)
                s.landloss[t0, r1] = (0.0)
                s.cumlandloss[t0, r1] = (0.0)
                s.cumwetlandloss[t0, r1] = (0.0)
                s.wetlandgrowth[t0, r1] = (0.0)

        else:

            ds = (s.sea[t] - s.sea[t - 1])

            for r in dimensions.GetValuesOfRegion():
                ypc = (s.income[t, r] / s.population[t, r] * 1000.0)
                ypcprev = (
                    s.income[t - 1, r] / s.population[t - 1, r] * 1000.0)
                ypcgrowth = (ypc / ypcprev - 1.0)

                if (t == Timestep.FromYear(1951)):
                    ypcgrowth = (0)

                incomedens = (s.income[t, r] / s.area[t, r])

                incomedensprev = (s.income[t - 1, r] / s.area[t - 1, r])

                incomedensgrowth = (incomedens / incomedensprev - 1.0)

                popdens = (s.population[t, r] / s.area[t, r] * 1000000.0)
                popdensprev = (
                    s.population[t - 1, r] / s.area[t - 1, r] * 1000000.0)
                popdensgrowth = (popdens / popdensprev - 1.0)

                s.dryval[t, r] = (
                    s.dvbm * math.pow(incomedens / s.incdens, s.dvydl))

                s.wetval[t, r] = (s.wvbm *
                                  math.pow(ypc / s.slrwvypc0, s.wvel) *
                                  math.pow(popdens / s.slrwvpopdens0, s.wvpdl) *
                                  math.pow((s.wetland90[r] - s.cumwetlandloss[t - 1, r]) / s.wetland90[r], s.wvsl))

                potCumLandloss = (
                    min(s.maxlandloss[r], s.cumlandloss[t - 1, r] + s.dlbm[r] * math.pow(s.sea[t], s.drylandlossparam[r])))

                potLandloss = (potCumLandloss - s.cumlandloss[t - 1, r])

                if (ds < 0):

                    s.npprotcost[t, r] = (0)
                    s.npwetcost[t, r] = (0)
                    s.npdrycost[t, r] = (0)
                    s.protlev[t, r] = (0)

                elif ((1.0 + s.slrprtp[r] + ypcgrowth) < 0.0):

                    s.npprotcost[t, r] = (0)
                    s.npwetcost[t, r] = (0)
                    s.npdrycost[t, r] = (0)
                    s.protlev[t, r] = (0)

                elif (((1.0 + s.dvydl * incomedensgrowth) < 0.0)):

                    s.npprotcost[t, r] = (0)
                    s.npwetcost[t, r] = (0)
                    s.npdrycost[t, r] = (0)
                    s.protlev[t, r] = (0)

                elif ((1.0 / (1.0 + s.slrprtp[r] + ypcgrowth)) >= 1):

                    s.npprotcost[t, r] = (0)
                    s.npwetcost[t, r] = (0)
                    s.npdrycost[t, r] = (0)
                    s.protlev[t, r] = (0)

                elif (((1.0 + s.dvydl * incomedensgrowth) / (1.0 + s.slrprtp[r] + ypcgrowth)) >= 1.0):

                    s.npprotcost[t, r] = (0)
                    s.npwetcost[t, r] = (0)
                    s.npdrycost[t, r] = (0)
                    s.protlev[t, r] = (1)

                elif (((1.0 + s.wvel * ypcgrowth + s.wvpdl * popdensgrowth + s.wvsl * s.wetlandgrowth[t - 1, r]) / (1.0 + s.slrprtp[r] + ypcgrowth)) >= 1.0):

                    s.npprotcost[t, r] = (0)
                    s.npwetcost[t, r] = (0)
                    s.npdrycost[t, r] = (0)
                    s.protlev[t, r] = (0)

                else:

                    s.npprotcost[t, r] = (
                        s.pc[r] * ds * (1.0 + s.slrprtp[r] + ypcgrowth) / (s.slrprtp[r] + ypcgrowth))

                    if ((1.0 + s.wvel * ypcgrowth + s.wvpdl * popdensgrowth + s.wvsl * s.wetlandgrowth[t - 1, r]) < 0.0):
                        s.npwetcost[t, r] = (0)
                    else:
                        s.npwetcost[t, r] = (s.wmbm[r] * ds * s.wetval[t, r] * (1.0 + s.slrprtp[r] + ypcgrowth) / (s.slrprtp[
                                             r] + ypcgrowth - s.wvel * ypcgrowth - s.wvpdl * popdensgrowth - s.wvsl * s.wetlandgrowth[t - 1, r]))

                    if ((1.0 + s.dvydl * incomedensgrowth) < 0.0):
                        s.npdrycost[t, r] = (0)
                    else:
                        s.npdrycost[t, r] = (potLandloss * s.dryval[t, r] * (1 + s.slrprtp[
                                             r] + ypcgrowth) / (s.slrprtp[r] + ypcgrowth - s.dvydl * incomedensgrowth))

                    s.protlev[t, r] = (
                        max(0.0, 1.0 - 0.5 * (s.npprotcost[t, r] + s.npwetcost[t, r]) / s.npdrycost[t, r]))

                    if (s.protlev[t, r] > 1):
                        raise Exception("protlevel >1 should not happen")

                s.wetlandloss[t, r] = (min(
                    s.wlbm[r] * ds + s.protlev[t, r] * s.wmbm[r] * ds,
                    s.wetmax[r] - s.cumwetlandloss[t - 1, r]))

                s.cumwetlandloss[t, r] = (
                    s.cumwetlandloss[t - 1, r] + s.wetlandloss[t, r])

                s.wetlandgrowth[t, r] = (
                    (s.wetland90[r] - s.cumwetlandloss[t, r]) / (s.wetland90[r] - s.cumwetlandloss[t - 1, r]) - 1.0)

                s.wetcost[t, r] = (s.wetval[t, r] * s.wetlandloss[t, r])

                s.landloss[t, r] = ((1.0 - s.protlev[t, r]) * potLandloss)

                s.cumlandloss[t, r] = (
                    s.cumlandloss[t - 1, r] + s.landloss[t, r])
                s.drycost[t, r] = (s.dryval[t, r] * s.landloss[t, r])

                s.protcost[t, r] = (s.protlev[t, r] * s.pc[r] * ds)

                if (s.landloss[t, r] < 0):
                    s.leave[t, r] = (0)
                else:
                    s.leave[t, r] = (s.coastpd[r] * popdens * s.landloss[t, r])

                s.leavecost[t, r] = (
                    s.emcst * ypc * s.leave[t, r] / 1000000000)

            for destination in dimensions.GetValuesOfRegion():
                enter = (0.0)
                for source in dimensions.GetValuesOfRegion():

                    enter += s.leave[t, source] * s.imigrate[
                        source, destination]

                s.enter[t, destination] = (enter)

            for r in dimensions.GetValuesOfRegion():
                ypc = (s.income[t, r] / s.population[t, r] * 1000.0)
                s.entercost[t, r] = (
                    s.immcst * ypc * s.enter[t, r] / 1000000000)


behavior_classes = [ImpactSeaLevelRiseComponent]
