# This file was automatically generated by converter.py on
# 2013-05-31 13:51:11.729127. Think long and hard before
# attempting to modify it.

from components.helpers import *


class IScenarioUncertaintyState(Parameters):
    pgrowth = IVariable2Dimensional('pgrowth', [
                                    'Timestep', 'Region'], 'double', None)
    ypcgrowth = IVariable2Dimensional('ypcgrowth', [
                                      'Timestep', 'Region'], 'double', None)
    aeei = IVariable2Dimensional('aeei', [
                                 'Timestep', 'Region'], 'double', None)
    acei = IVariable2Dimensional('acei', [
                                 'Timestep', 'Region'], 'double', None)
    forestemm = IVariable2Dimensional(
        'forestemm', ['Timestep', 'Region'], 'double', None)
    scenpgrowth = IParameter2Dimensional('scenpgrowth', [
                                         'Timestep', 'Region'], 'double', None)
    scenypcgrowth = IParameter2Dimensional(
        'scenypcgrowth', ['Timestep', 'Region'], 'double', None)
    scenaeei = IParameter2Dimensional('scenaeei', [
                                      'Timestep', 'Region'], 'double', None)
    scenacei = IParameter2Dimensional('scenacei', [
                                      'Timestep', 'Region'], 'double', None)
    scenforestemm = IParameter2Dimensional(
        'scenforestemm', ['Timestep', 'Region'], 'double', None)
    ecgradd = IParameter1Dimensional('ecgradd', ['Region'], 'double', None)
    pgadd = IParameter1Dimensional('pgadd', ['Region'], 'double', None)
    aeeiadd = IParameter1Dimensional('aeeiadd', ['Region'], 'double', None)
    aceiadd = IParameter1Dimensional('aceiadd', ['Region'], 'double', None)
    foremadd = IParameter1Dimensional('foremadd', ['Region'], 'double', None)

    options = [pgrowth, ypcgrowth, aeei, acei,
               forestemm, scenpgrowth, scenypcgrowth, scenaeei, scenacei, scenforestemm, ecgradd, pgadd, aeeiadd, aceiadd, foremadd]


class ScenarioUncertaintyComponent(Behaviors):
    state_class = IScenarioUncertaintyState

    def run(self, state, clock):

        s = (state)
        t = (clock.Current)

        yearsFromUncertaintyStart = (t.Value - s.timeofuncertaintystart.Value)
        sdTimeFactor = ((yearsFromUncertaintyStart / 50.0) / (
            1.0 + (yearsFromUncertaintyStart / 50.0)))

        for r in dimensions.GetValuesOfRegion():

            s.ypcgrowth[t, r] = (s.scenypcgrowth[t, r] + (
                t >= s.timeofuncertaintystart and s.ecgradd[r] * sdTimeFactor or 0.0))
            s.pgrowth[t, r] = (s.scenpgrowth[t, r] + (
                t >= s.timeofuncertaintystart and s.pgadd[r] * sdTimeFactor or 0.0))
            s.aeei[t, r] = (s.scenaeei[t, r] + (
                t >= s.timeofuncertaintystart and s.aeeiadd[r] * sdTimeFactor or 0.0))
            s.acei[t, r] = (s.scenacei[t, r] + (
                t >= s.timeofuncertaintystart and s.aceiadd[r] * sdTimeFactor or 0.0))
            s.forestemm[t, r] = (s.scenforestemm[t, r] + (
                t >= s.timeofuncertaintystart and s.foremadd[r] * sdTimeFactor or 0.0))


behavior_classes = [ScenarioUncertaintyComponent]
